# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-25 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageURL',
            field=models.CharField(default='www.google.com', max_length=50),
            preserve_default=False,
        ),
    ]
