# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-26 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageURL',
            field=models.CharField(max_length=500),
        ),
    ]
