# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-26 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20170826_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='imageURL',
            field=models.CharField(default='dd', max_length=500),
            preserve_default=False,
        ),
    ]
