# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-26 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details', '0004_stall_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Product')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Stall')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Product')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Stall')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('salePrice', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Product')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Stall')),
            ],
        ),
        migrations.CreateModel(
            name='StallHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Stall')),
            ],
        ),
    ]
